from transformers import AutoTokenizer
import torch
import argparse

def dtype_type(dtype_str):
    """Convert string to torch.dtype"""
    dtype_str = dtype_str.lower()
    if dtype_str == 'float16':
        return torch.float16
    elif dtype_str == 'float32':
        return torch.float32
    elif dtype_str == 'bfloat16':
        return torch.bfloat16
    raise argparse.ArgumentTypeError(f"Unsupported dtype: {dtype_str}")

RUNTIME_CFGS = ["quest", "hg"]

def inference(model, tokenizer, prompt, max_length, device):
    # Process prompt
    print(f"Prompt: {prompt}")
    inputs = tokenizer(prompt, return_tensors="pt").to(device)
    print(f"Input Sequence Length: {inputs.input_ids.shape[1]}")

    with torch.no_grad():
        generate_ids = model.generate(
            inputs.input_ids,
            max_length=max_length,  # Now configurable via CLI
            # use_cache=True 
            past_key_values=None
        )
    print("-" * 20)

    # Calculate the number of output tokens
    output_token_size = generate_ids.shape[1]  # Total tokens in the generated sequence
    input_token_size = inputs.input_ids.shape[1]  # Tokens in the input sequence
    generated_token_size = output_token_size - input_token_size  # Tokens generated by the model

    print(f"Total Output Token Size: {output_token_size}")
    print(f"Generated Token Size (excluding input): {generated_token_size}")

    print("Output: ", tokenizer.batch_decode(
        generate_ids, 
        skip_special_tokens=True, 
        clean_up_tokenization_spaces=False
    )[0])
    

if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    # Model and hardware configuration
    parser.add_argument("--model_path", type=str, 
        default="/fact_home/shiyiliu/coding/Quest/data/model/Llama-2-7b-chat-hf",
        help="Path to pretrained model")
    parser.add_argument("--device", type=str, default="cuda:0",
        help="Device to use (e.g., cuda:0, cpu)")
    parser.add_argument("--dtype", type=dtype_type, default="float16",
        help="Data type for computation (float16, float32, bfloat16)")

    # Quest-specific configuration
    parser.add_argument("--page_size", type=int, default=16,
        help="Page size for memory management")
    parser.add_argument("--max_seq_len", type=int, default=8192,
        help="Maximum sequence length supported")
    parser.add_argument("--token_budget", type=int, default=64,
        help="Token budget for memory allocation")

    # Generation configuration
    parser.add_argument("--max_length", type=int, default=2048,
        help="Maximum length for generated sequence")

    # Runtime method selection
    parser.add_argument("--method", choices=RUNTIME_CFGS, default="quest",
        help="Runtime method to use (quest or hg)")

    # Prompt configuration
    parser.add_argument("--prompt", type=str, 
        default="In an animal kingdom, the lion is the king. One day, the lion announces a competition to choose the most hardworking animal. The turtle, rabbit, monkey, zebra, and giraffe all decide to participate. After a day of observation, the lion notices that all the animals are working hard, except for the rabbit, who is sleeping. So why does the lion choose the rabbit as the most hardworking animal?",
        help="Input prompt for generation")

    args = parser.parse_args()

    # Initialize based on CLI arguments
    MODEL_PATH = args.model_path
    DEVICE = torch.device(args.device)
    DTYPE = args.dtype
    PAGE_SIZE = args.page_size
    MAX_SEQ_LEN = args.max_seq_len

    torch.set_default_dtype(DTYPE)
    tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)

    if args.method == "quest":
        from quest import LlamaForCausalLM
        model = LlamaForCausalLM.from_pretrained(
            MODEL_PATH, 
            device_map=DEVICE, 
            torch_dtype=DTYPE
        )
        # Initialize Quest Controller with CLI parameters
        model.quest_init(
            page_size=PAGE_SIZE,
            max_seq_len=MAX_SEQ_LEN,
            
            token_budget=args.token_budget
        )
        print(f"Page Size: {PAGE_SIZE}\nMax Seq Len: {MAX_SEQ_LEN}")
    else:
        from transformers import LlamaForCausalLM
        model = LlamaForCausalLM.from_pretrained(
            MODEL_PATH, 
            device_map=DEVICE, 
            torch_dtype=DTYPE
        )

    inference(
        model=model,
        tokenizer=tokenizer,
        prompt=args.prompt,
        max_length=args.max_length,
        device=DEVICE
    )